name: Continous Integration

on:
  push:
    branches:
      - main

jobs:
  versioning:
    uses: laboratorio-net/actions/.github/workflows/git-version.yaml@main

  build:
    uses: laboratorio-net/actions/.github/workflows/build-dotnet.yaml@main
    needs: Versioning
    with:
      solution-name: TestPipeLineNet.sln
      package-version: ${{needs.versioning.outputs.version}}
      dotnet-version: "10.0.x"
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}  

  tag:
    uses: laboratorio-net/actions/.github/workflows/create-tag.yaml@main
    needs: [versioning, build]
    with:
      version: ${{needs.versioning.outputs.version}}